version: '3.6'
services:

  app:
    image: elixircloud/foca-petstore:0.1.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FOCA_IMAGE: ${PY_VERSION:-3.10}
    restart: unless-stopped
    links:
      - mongodb
    command: bash -c "python app.py"
    ports:
      - "80:8080"

  mongodb:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - ./data/petstore/db:/data/db
    ports:
      - "27077:27017"
