version: '3.6'
services:
  foca-petstore-root:
    build:
      context: ../../
      dockerfile: docker/Dockerfile_py3.9
    image: foca-petstore-root:latest
  
  app:
    image: elixircloud/foca-petstore:latest
    depends_on:
      - foca-petstore-root
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - mongodb
    command: bash -c "python app.py"
    ports:
      - "80:8080"

  mongodb:
    image: mongo:3.6
    restart: unless-stopped
    volumes:
      - ./data/petstore/db:/data/db
    ports:
      - "27017:27017"
